In [30]:
import os
import pandas as pd
import numpy as np

from sklearn.tree import DecisionTreeClassifier # 모델-결정트리
from sklearn.metrics import accuracy_score #모델 평가함수 -> 정확도
from sklearn.model_selection import train_test_split # 데이터셋을 나누는 함수

## 데이터 불러오기

In [15]:
df = pd.read_csv('/aiffel/aiffel/dialect_data/Data_bySY/dataset_full_v1.csv')

In [16]:
df.head()

,text,dial,reg,pair
0,그 부주를 하기에는 조금 그렇지 (않아?),그 부주를 하기에는 조금 그렇지 (안?),jj,(안?)/(않아?)
1,그리고 거기서 밥을 먹을지도 (모르겠어.),그리고 거기서 밥을 먹을지도 (모르겐.),jj,(모르겐.)/(모르겠어.)
2,왜냐하면은 밥이 안 나온다고 (들었어.),왜냐하면은 밥이 안 나온다고 (들언.),jj,(들언.)/(들었어.)
3,토요일 날에 토요일날에 잔치를 하고 일요일 날에 식을 (올린대.),토요일 날에 토요일날에 잔치를 하고 일요일 날에 식을 (올린댄.),jj,(올린댄.)/(올린대.)
4,그럼 어떻게 혼자 아 (혼자래.),그럼 어떻게 혼자 아 (혼자랜.),jj,(혼자랜.)/(혼자래.)

In [17]:
df.tail()

,text,dial,reg,pair
2994177,내가 진짜 (이거) 왜 이러나? 나 병든 거 아니나? 진짜?,내가 진짜 (이그) 왜 이러나? 나 병든 거 아니나? 진짜?,kw,(이그)/(이거)
2994178,네 오늘은 없어요 (어디) 나가시나 (보죠?),네 오늘은 없어요 (어데) 나가시나 (부죠?),kw,(어데)/(어디) (부죠?)/(보죠?)
2994179,(막내놈) 아르바이트하는데 나 좀 둘러보구요. (사돈댁에) 다,(끝네미놈) 아르바이트하는데 나 좀 둘러보구요. (사둔댁에) 다,kw,(끝네미놈)/(막내놈) (사둔댁에)/(사돈댁에)
2994180,네 서울 입성 신고를 해야 할 거 (아니에요.),네 서울 입성 신고를 해야 할 거 (아닙니꺼.),kw,(아닙니꺼.)/(아니에요.)
2994181,저 언니네 (지금) 안 계실걸요?,저 언니네 (지굼) 안 계실걸요?,kw,(지굼)/(지금)

In [18]:
df.shape

(2994182, 4)

## 데이터 정제 
> 1. 결측치 확인 / 제거 
2. 중복 데이터 확인 / 제거

In [21]:
df.isnull().sum()

text    2
dial    0
reg     0
pair    0
dtype: int64

In [23]:
df.dropna()

,text,dial,reg,pair
0,그 부주를 하기에는 조금 그렇지 (않아?),그 부주를 하기에는 조금 그렇지 (안?),jj,(안?)/(않아?)
1,그리고 거기서 밥을 먹을지도 (모르겠어.),그리고 거기서 밥을 먹을지도 (모르겐.),jj,(모르겐.)/(모르겠어.)
2,왜냐하면은 밥이 안 나온다고 (들었어.),왜냐하면은 밥이 안 나온다고 (들언.),jj,(들언.)/(들었어.)
3,토요일 날에 토요일날에 잔치를 하고 일요일 날에 식을 (올린대.),토요일 날에 토요일날에 잔치를 하고 일요일 날에 식을 (올린댄.),jj,(올린댄.)/(올린대.)
4,그럼 어떻게 혼자 아 (혼자래.),그럼 어떻게 혼자 아 (혼자랜.),jj,(혼자랜.)/(혼자래.)
...,...,...,...,...
2994177,내가 진짜 (이거) 왜 이러나? 나 병든 거 아니나? 진짜?,내가 진짜 (이그) 왜 이러나? 나 병든 거 아니나? 진짜?,kw,(이그)/(이거)
2994178,네 오늘은 없어요 (어디) 나가시나 (보죠?),네 오늘은 없어요 (어데) 나가시나 (부죠?),kw,(어데)/(어디) (부죠?)/(보죠?)
2994179,(막내놈) 아르바이트하는데 나 좀 둘러보구요. (사돈댁에) 다,(끝네미놈) 아르바이트하는데 나 좀 둘러보구요. (사둔댁에) 다,kw,(끝네미놈)/(막내놈) (사둔댁에)/(사돈댁에)
2994180,네 서울 입성 신고를 해야 할 거 (아니에요.),네 서울 입성 신고를 해야 할 거 (아닙니꺼.),kw,(아닙니꺼.)/(아니에요.)
2994181,저 언니네 (지금) 안 계실걸요?,저 언니네 (지굼) 안 계실걸요?,kw,(지굼)/(지금)

In [25]:
df.drop_duplicates(subset='text', keep=False, inplace=False, ignore_index=True)

,text,dial,reg,pair
0,그 부주를 하기에는 조금 그렇지 (않아?),그 부주를 하기에는 조금 그렇지 (안?),jj,(안?)/(않아?)
1,그리고 거기서 밥을 먹을지도 (모르겠어.),그리고 거기서 밥을 먹을지도 (모르겐.),jj,(모르겐.)/(모르겠어.)
2,왜냐하면은 밥이 안 나온다고 (들었어.),왜냐하면은 밥이 안 나온다고 (들언.),jj,(들언.)/(들었어.)
3,토요일 날에 토요일날에 잔치를 하고 일요일 날에 식을 (올린대.),토요일 날에 토요일날에 잔치를 하고 일요일 날에 식을 (올린댄.),jj,(올린댄.)/(올린대.)
4,그럼 어떻게 혼자 아 (혼자래.),그럼 어떻게 혼자 아 (혼자랜.),jj,(혼자랜.)/(혼자래.)
...,...,...,...,...
2367670,내가 진짜 (이거) 왜 이러나? 나 병든 거 아니나? 진짜?,내가 진짜 (이그) 왜 이러나? 나 병든 거 아니나? 진짜?,kw,(이그)/(이거)
2367671,네 오늘은 없어요 (어디) 나가시나 (보죠?),네 오늘은 없어요 (어데) 나가시나 (부죠?),kw,(어데)/(어디) (부죠?)/(보죠?)
2367672,(막내놈) 아르바이트하는데 나 좀 둘러보구요. (사돈댁에) 다,(끝네미놈) 아르바이트하는데 나 좀 둘러보구요. (사둔댁에) 다,kw,(끝네미놈)/(막내놈) (사둔댁에)/(사돈댁에)
2367673,네 서울 입성 신고를 해야 할 거 (아니에요.),네 서울 입성 신고를 해야 할 거 (아닙니꺼.),kw,(아닙니꺼.)/(아니에요.)
2367674,저 언니네 (지금) 안 계실걸요?,저 언니네 (지굼) 안 계실걸요?,kw,(지굼)/(지금)

In [26]:
df.drop_duplicates(subset='dial', keep=False, inplace=False, ignore_index=True)

,text,dial,reg,pair
0,그 부주를 하기에는 조금 그렇지 (않아?),그 부주를 하기에는 조금 그렇지 (안?),jj,(안?)/(않아?)
1,그리고 거기서 밥을 먹을지도 (모르겠어.),그리고 거기서 밥을 먹을지도 (모르겐.),jj,(모르겐.)/(모르겠어.)
2,왜냐하면은 밥이 안 나온다고 (들었어.),왜냐하면은 밥이 안 나온다고 (들언.),jj,(들언.)/(들었어.)
3,토요일 날에 토요일날에 잔치를 하고 일요일 날에 식을 (올린대.),토요일 날에 토요일날에 잔치를 하고 일요일 날에 식을 (올린댄.),jj,(올린댄.)/(올린대.)
4,그럼 어떻게 혼자 아 (혼자래.),그럼 어떻게 혼자 아 (혼자랜.),jj,(혼자랜.)/(혼자래.)
...,...,...,...,...
2396115,요 째그만 한 건 (아마) (막내) 건가 부다 아유 째끄만 해,요 째그만 한 건 (아매) (끝네미) 건가 부다 아유 째끄만 해,kw,(아매)/(아마) (끝네미)/(막내)
2396116,내가 진짜 (이거) 왜 이러나? 나 병든 거 아니나? 진짜?,내가 진짜 (이그) 왜 이러나? 나 병든 거 아니나? 진짜?,kw,(이그)/(이거)
2396117,네 오늘은 없어요 (어디) 나가시나 (보죠?),네 오늘은 없어요 (어데) 나가시나 (부죠?),kw,(어데)/(어디) (부죠?)/(보죠?)
2396118,(막내놈) 아르바이트하는데 나 좀 둘러보구요. (사돈댁에) 다,(끝네미놈) 아르바이트하는데 나 좀 둘러보구요. (사둔댁에) 다,kw,(끝네미놈)/(막내놈) (사둔댁에)/(사돈댁에)
2396119,저 언니네 (지금) 안 계실걸요?,저 언니네 (지굼) 안 계실걸요?,kw,(지굼)/(지금)

In [27]:
df.drop_duplicates(subset='pair', keep=False, inplace=False, ignore_index=True)

,text,dial,reg,pair
0,그럼 어떻게 혼자 아 (혼자래.),그럼 어떻게 혼자 아 (혼자랜.),jj,(혼자랜.)/(혼자래.)
1,편지 안써도 될 (꺼야.),편지 안써도 될 (삘.),jj,(삘.)/(꺼야.)
2,음 걔 (어떻게) 누가 키우냐?,음 걔 (어뜨) 누가 키우냐?,jj,(어뜨)/(어떻게)
3,다 (팔아넘기고) 그 뭐 (진짜.),다 (팔아넘겨그냉) 그 뭐 (진짜이.),jj,(팔아넘겨그냉)/(팔아넘기고) (진짜이.)/(진짜.)
4,그래도 예로부터 조상 (땅은) 팔지 (말라고) (말했어.),그래도 예로부터 조상 (땅은이) 팔지 (말랭) (가*라쪄.),jj,(땅은이)/(땅은) (말랭)/(말라고) (가*라쪄.)/(말했어.)
...,...,...,...,...
864390,(아버지) (돈많이) 벌면 나 옷 사주세요?,(아부지) (돈마이) 벌면 나 옷 사주세요?,kw,(아부지)/(아버지) (돈마이)/(돈많이)
864391,이 헐렁한 건 (아버지) 것 이건 @이름1이 (신랑) 것,이 헐렁한 건 (아부지) 것 이건 @이름1이 (신랭) 것,kw,(아부지)/(아버지) (신랭)/(신랑)
864392,요 째그만 한 건 (아마) (막내) 건가 부다 아유 째끄만 해,요 째그만 한 건 (아매) (끝네미) 건가 부다 아유 째끄만 해,kw,(아매)/(아마) (끝네미)/(막내)
864393,(막내놈) 아르바이트하는데 나 좀 둘러보구요. (사돈댁에) 다,(끝네미놈) 아르바이트하는데 나 좀 둘러보구요. (사둔댁에) 다,kw,(끝네미놈)/(막내놈) (사둔댁에)/(사돈댁에)
864394,네 서울 입성 신고를 해야 할 거 (아니에요.),네 서울 입성 신고를 해야 할 거 (아닙니꺼.),kw,(아닙니꺼.)/(아니에요.)

In [34]:
df[df['reg'].str.contains('jj', na = False)]

,text,dial,reg,pair
0,그 부주를 하기에는 조금 그렇지 (않아?),그 부주를 하기에는 조금 그렇지 (안?),jj,(안?)/(않아?)
1,그리고 거기서 밥을 먹을지도 (모르겠어.),그리고 거기서 밥을 먹을지도 (모르겐.),jj,(모르겐.)/(모르겠어.)
2,왜냐하면은 밥이 안 나온다고 (들었어.),왜냐하면은 밥이 안 나온다고 (들언.),jj,(들언.)/(들었어.)
3,토요일 날에 토요일날에 잔치를 하고 일요일 날에 식을 (올린대.),토요일 날에 토요일날에 잔치를 하고 일요일 날에 식을 (올린댄.),jj,(올린댄.)/(올린대.)
4,그럼 어떻게 혼자 아 (혼자래.),그럼 어떻게 혼자 아 (혼자랜.),jj,(혼자랜.)/(혼자래.)
...,...,...,...,...
1172944,다른 건 다 작동도 안 되는 (거야),다른 건 다 작동도 안 되는 (거),jj,(거)/(거야)
1172945,고객 응대도 안 해주는 (거야),고객 응대도 안 해주는 (거),jj,(거)/(거야)
1172946,얼마 (나왔는데?),얼마 (나완?),jj,(나완?)/(나왔는데?)
1172947,차라리 (샀으면) (어떻게) 안 (하는데),차라리 (사시민) (어떵) 안 (하는디),jj,(사시민)/(샀으면) (어떵)/(어떻게) (하는디)/(하는데)
1172948,끊어 (버리자),끊어 (불자),jj,(불자)/(버리자)

In [46]:
df.loc[1172948:1172949,:'reg' ]

                          text                   dial reg
1172948               끊어 (버리자)                끊어 (불자)  jj
1172949  지금 (네가) 가진 성격이 마음에 듦?  지금 (니가) 가진 성격이 마음에 듦?  gs

In [38]:
print(df['reg'].unique())

['jj' 'gs' 'cc' 'jd' 'kw']

In [40]:
print(df['reg'].value_counts())

jj    1172949
kw     915155
gs     334780
jd     295364
cc     275934
Name: reg, dtype: int64

## ['reg'] cloumn에서 지역별로 분리

In [61]:
jj_sample = df[df['reg'] == 'jj']

In [62]:
gs_sample = df[df['reg'] == 'gs']

In [63]:
cc_sample = df[df['reg'] == 'cc']

In [64]:
jd_sample = df[df['reg'] == 'jd']

In [65]:
kw_sample = df[df['reg'] == 'kw']

In [71]:
kw_sample

,text,dial,reg,pair
2079027,(너무) 정신이 없어서 그랬나 (보다.),(너머) 정신이 없어서 그랬나 (부다.),kw,(너머)/(너무) (부다.)/(보다.)
2079028,아냐 내가 찾아 먹을께 @이름씨 (세수해.),아냐 내가 찾아 먹을께 @이름씨 (세시해.),kw,(세시해.)/(세수해.)
2079029,(오늘) (수고하셨습니다.),(오놀) (수구하셨습니다.),kw,(오놀)/(오늘) (수구하셨습니다.)/(수고하셨습니다.)
2079030,(오늘) (수고하셨습니다.),(오놀) (수구하셨습니다.),kw,(오놀)/(오늘) (수구하셨습니다.)/(수고하셨습니다.)
2079031,피곤할 (테니까) (이거) 한 잔 쭉 마시고 푹 자버려.,피곤할 (테이까) (이그) 한 잔 쭉 마시고 푹 자버려.,kw,(테이까)/(테니까) (이그)/(이거)
...,...,...,...,...
2994177,내가 진짜 (이거) 왜 이러나? 나 병든 거 아니나? 진짜?,내가 진짜 (이그) 왜 이러나? 나 병든 거 아니나? 진짜?,kw,(이그)/(이거)
2994178,네 오늘은 없어요 (어디) 나가시나 (보죠?),네 오늘은 없어요 (어데) 나가시나 (부죠?),kw,(어데)/(어디) (부죠?)/(보죠?)
2994179,(막내놈) 아르바이트하는데 나 좀 둘러보구요. (사돈댁에) 다,(끝네미놈) 아르바이트하는데 나 좀 둘러보구요. (사둔댁에) 다,kw,(끝네미놈)/(막내놈) (사둔댁에)/(사돈댁에)
2994180,네 서울 입성 신고를 해야 할 거 (아니에요.),네 서울 입성 신고를 해야 할 거 (아닙니꺼.),kw,(아닙니꺼.)/(아니에요.)
2994181,저 언니네 (지금) 안 계실걸요?,저 언니네 (지굼) 안 계실걸요?,kw,(지굼)/(지금)

## 분리된 태그별 random 으로 1000개씩 추출

In [75]:
jj_df = jj_sample.sample(n=1000, 
                         replace=False, 
                         weights=None, 
                         random_state=220, axis=0, ignore_index=True)

In [76]:
gs_df = gs_sample.sample(n=1000,
                         replace=False, 
                         weights=None, 
                         random_state=220, axis=0, ignore_index=True)

In [78]:
cc_df = cc_sample.sample(n=1000, 
                         replace=False, 
                         weights=None, 
                         random_state=220, axis=0, ignore_index=True)

In [79]:
jd_df = cc_sample.sample(n=1000, 
                         replace=False, 
                         weights=None, 
                         random_state=220, axis=0, ignore_index=True)

In [86]:
kw_df = cc_sample.sample(n=1000, 
                         replace=False, 
                         weights=None, 
                         random_state=220, axis=0, ignore_index=True)

In [87]:
jj_df

,text,dial,reg,pair
0,맞아 월정까진 (괜찮아) 월정은,맞아 월정까진 (괜찮애) 월정은,jj,(괜찮애)/(괜찮아)
1,(서기만) (하면) 아래가 그냥 (묵직해서) 뭐 (하면) (뭐가) 그냥,(섬만) (허민) 아래가 그냥 (묵직허영) 뭐 (허면은) (무시것이) 그냥,jj,(섬만)/(서기만) (허민)/(하면) (묵직허영)/(묵직해서) (허면은)/(하면) ...
2,탄생에서 돌아가시길 때까지 보니까 딱 칠 계단 만에 오면 (되겠네.),탄생에서 돌아가시길 때까지 보니까 딱 칠 계단 만에 오면 (되킁게.),jj,(되킁게.)/(되겠네.)
3,(그니까),(그니깐),jj,(그니깐)/(그니까)
4,뭐 (하면서) 놀아?,뭐 (하멍) 놀아?,jj,(하멍)/(하면서)
...,...,...,...,...
995,나랑 &name이랑 (쟤랑) (간데가) 거기,나랑 &name이랑 (자이랑) (간디가) 거기,jj,(자이랑)/(쟤랑) (간디가)/(간데가)
996,밖에 완전 (꽝꽝얼었어),밖에 완전 (꽝꽝얼언),jj,(꽝꽝얼언)/(꽝꽝얼었어)
997,그래서 나 아는 (친구도) 제주도 (친군데),그래서 나 아는 (아이도) 제주도 (아인디),jj,(아이도)/(친구도) (아인디)/(친군데)
998,여기서 온 문자가 막 (가네),여기서 온 문자가 막 (감신게),jj,(감신게)/(가네)
999,(예),(맞수다),jj,(맞수다)/(맞아)(#예)/(예)

In [106]:
df_list = [ jj_df, gs_df, cc_df, jd_df, kw_df]
df_merge = pd.concat(df_list, ignore_index = True)

In [110]:
# ['reg'] column에서 각 태그별 랜덤으로 1000개의 샘플을 추출 
# df_merge로 DataFrame 합쳤음
df_merge.shape

(5000, 4)

## Train/vaildation set으로 분리

In [111]:
X, y = df, df_merge
X.shape , y.shape


X_trin, X_test, y_train, y_test = train_test_split(X, y, 
                                                  test_size= 0.25,
                                                  stratify = y,
                                                  random_state = 1)

ValueError: Found input variables with inconsistent numbers of samples: [2994182, 5000]

In [ ]:

X_train, X_val , y_train , y_val = train_test_split(X_train , 
                                                    y_train,
                                                   test_size = 0.2 . 
                                                   stratify = y_train,
                                                   random_state = 1)